### PR TITLE
Adapt to changes in TCK

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/107

### CODE REVIEW

**Comment by trisberg** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-deployer/pull/196

**Comment by trisberg** [comment]
LGTM, can merge after spring-cloud/spring-cloud-deployer#196 is merged

**Comment by ilayaperumalg** [comment]
Merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as c7c2f5fcdb8ee855ceb480106cb1dee6087fdc8d

**Pull request closed without merging**
