### PR TITLE
Map cmd line args when using boot entryPointStyle

### LINKED ISSUE #209: Kubernetes Server/Deployer pushes app properties command line
_From @cppwfs on March 30, 2018 19:57_

Problem with this is that database passwords show up in the clear for batch jobs.  Also that means that the passwords are stored in the repository for task-executions as well as batch.

Step to reproduce:
1) Create Task Definition `foo` with timestamp-batch.
2) Launch `foo`
3) Look at task-execution for the launch. You will see the arguments with the password redacted.
4) Look at the Job Execution Details.  Password is shown in the clear.

This does not occur on local server.

_Copied from original issue: spring-cloud/spring-cloud-dataflow-server-kubernetes#270_

### LINKED ISSUE #212: Map command line args when using boot entry point style
When using entry point `boot` to store application properties in `SPRING_APPLICATION_JSON`, provided command line arguments are not included when building the container. This causes issues when an application wants to make use of `SPRING_APPLICATION_JSON` but also pass command line arguments similar to `exec`. Entry point `shell` is left unchanged as command line arguments are not appended for this style of Docker `ENTRYPOINT`. I've opened a seperate issue to document entry point style usage (https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/211) as there is some research to be done.

### PR DESCRIPTION
**Pull request by chrisjs**
Fixes #212
Fixes #209

### CODE REVIEW

**Comment by chrisjs** [comment]
documentation issue at: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/211

**Comment by ilayaperumalg** [comment]
Looks like the job parameters are still not redacted at the job executions page.

**Comment by chrisjs** [comment]
where are you seeing them? I'm doing:

```
dataflow:>app register --name timestamp --type task --uri docker://blah:latest
Successfully registered application 'task:timestamp'
dataflow:>task create --name blah --definition "timestamp"
Created new task 'blah'
dataflow:>task launch --name blah --properties "deployer.timestamp.kubernetes.entryPointStyle=boot"
Launched task 'blah'
dataflow:>task execution status --id 1
╔══════════════════════╤═══════════════════════════════════╗
║         Key          │               Value               ║
╠══════════════════════╪═══════════════════════════════════╣
║Id                    │1                                  ║
║Name                  │blah                               ║
║Arguments             │[--spring.cloud.task.executionid=1]║
║Job Execution Ids     │[1, 2]                             ║
║Start Time            │Wed Apr 18 10:00:21 EDT 2018       ║
║End Time              │Wed Apr 18 10:00:21 EDT 2018       ║
║Exit Code             │0                                  ║
║Exit Message          │                                   ║
║Error Message         │                                   ║
║External Execution Id │blah-ewz8k1gznw                    ║
╚══════════════════════╧═══════════════════════════════════╝

dataflow:>job execution display --id1
╔═══════════════════════════════════════╤════════════════════════════╗
║                  Key                  │           Value            ║
╠═══════════════════════════════════════╪════════════════════════════╣
║Job Execution Id                       │1                           ║
║Task Execution Id                      │1                           ║
║Task Instance Id                       │1                           ║
║Job Name                               │job1                        ║
║Create Time                            │Wed Apr 18 10:00:21 EDT 2018║
║Start Time                             │Wed Apr 18 10:00:21 EDT 2018║
║End Time                               │Wed Apr 18 10:00:21 EDT 2018║
║Running                                │false                       ║
║Stopping                               │false                       ║
║Step Execution Count                   │1                           ║
║Execution Status                       │COMPLETED                   ║
║Exit Status                            │COMPLETED                   ║
║Exit Message                           │                            ║
║Definition Status                      │Created                     ║
║Job Parameters                         │                            ║
║-spring.cloud.task.executionid(STRING) │1                           ║
╚═══════════════════════════════════════╧════════════════════════════╝

dataflow:>job execution display --id 2
╔═══════════════════════════════════════╤════════════════════════════╗
║                  Key                  │           Value            ║
╠═══════════════════════════════════════╪════════════════════════════╣
║Job Execution Id                       │2                           ║
║Task Execution Id                      │1                           ║
║Task Instance Id                       │2                           ║
║Job Name                               │job2                        ║
║Create Time                            │Wed Apr 18 10:00:21 EDT 2018║
║Start Time                             │Wed Apr 18 10:00:21 EDT 2018║
║End Time                               │Wed Apr 18 10:00:21 EDT 2018║
║Running                                │false                       ║
║Stopping                               │false                       ║
║Step Execution Count                   │1                           ║
║Execution Status                       │COMPLETED                   ║
║Exit Status                            │COMPLETED                   ║
║Exit Message                           │                            ║
║Definition Status                      │Created                     ║
║Job Parameters                         │                            ║
║-spring.cloud.task.executionid(STRING) │1                           ║
╚═══════════════════════════════════════╧════════════════════════════╝

dataflow:>
``` 

and I don't see the cmd args in question as job params with the exception of `spring.cloud.task.executionid` which is passed as a cmd line arg -- same if i go to the dataflow dashboard for jobs/tasks.

**Comment by ilayaperumalg** [comment]
@chrisjs this is what I am trying (with the command line arg that needs to be redacted :

```
dataflow:>task create a1 --definition "timestamp-batch"
Created new task 'a1'
dataflow:>task launch a1 --arguments "--test1.password=test" --properties "deployer.timestamp-batch.kubernetes.entryPointStyle=boot"
Launched task 'a1'

dataflow:>job execution display --id 1
╔═══════════════════════════════════════╤════════════════════════════╗
║                  Key                  │           Value            ║
╠═══════════════════════════════════════╪════════════════════════════╣
║Job Execution Id                       │1                           ║
║Task Execution Id                      │1                           ║
║Task Instance Id                       │1                           ║
║Job Name                               │job1                        ║
║Create Time                            │Wed Apr 18 18:54:40 IST 2018║
║Start Time                             │Wed Apr 18 18:54:40 IST 2018║
║End Time                               │Wed Apr 18 18:54:40 IST 2018║
║Running                                │false                       ║
║Stopping                               │false                       ║
║Step Execution Count                   │1                           ║
║Execution Status                       │COMPLETED                   ║
║Exit Status                            │COMPLETED                   ║
║Exit Message                           │                            ║
║Definition Status                      │Created                     ║
║Job Parameters                         │                            ║
║-test1.password(STRING)                │test                        ║
║-spring.cloud.task.executionid(STRING) │1                           ║
╚═══════════════════════════════════════╧════════════════════════════╝

```

**Comment by ilayaperumalg** [comment]
I think I understand the fix now. The application properties are pushed in SAJ when using `boot` entryPointStyle but the cmd line arguments would not be redacted (as we expect the sensitive properties to be specified as app properties instead of cmd line args).

LGTM, merging.

**Pull request merged**
